//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace LEADMaintenance.Screens {
    
    
    public partial class Main {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new LEADMaintenance.Screens.Site Master {
            get {
                return ((LEADMaintenance.Screens.Site)(base.Master));
            }
        }
    }
}
